package com.filmplanner.dao.postgre;

import com.filmplanner.dao.AbstractDAOFactory;
import com.filmplanner.dao.ProjectDAO;
import com.filmplanner.dao.UserDAO;
import com.filmplanner.models.Project;
import com.filmplanner.models.User;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;

public class PostgreProjectDAO implements ProjectDAO {

    private Connection connection;

    public PostgreProjectDAO(Connection connection) {
        this.connection = connection;
    }

    /*
    Methods
     */

    /**
     * Creates a new Project in the database given an instance of a Project.
     *
     * @param project the Project which will be inserted inside the database
     * @return an instance of the created project with the id generated by the database; null if there was an SQLException
     */
    @Override
    public Project create(Project project) {
        Project createdProject = null;
        try {
            // project insertion statement preparation
            String query = "INSERT INTO project (name, description) VALUES (?, ?)";
            PreparedStatement statement = this.connection.prepareStatement(query, Statement.RETURN_GENERATED_KEYS);
            statement.setString(1, project.getName());
            statement.setString(2, project.getDescription());

            if (statement.executeUpdate() > 0) { // if no rows were altered the request did nothing
                ResultSet resultSet = statement.getGeneratedKeys();
                resultSet.next();
                Long generatedProjectId = resultSet.getLong("project_id");

                this.addManagers(generatedProjectId, project.getManagers());

                // TODO for each shoot: create shoot based on project id (ShootDAO)

                // TODO for each paperwork: create paperwork based on project id (PaperworkDAO)

                // TODO add client to project (ClientDAO)

                createdProject = new Project(generatedProjectId, project);
                resultSet.close();
                statement.close();
            }

            statement.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return createdProject;
    }

    /**
     * Gets a Project by its id.
     *
     * @param id the Project's id
     * @return the Project corresponding to the given id or null if the id doesn't correspond to any Project.
     */
    public Project findById(Long id) {
        Project foundProject = null;
        if (id != null) {
            try {

                // Finds project
                String query = "SELECT project_id, name, description FROM project WHERE project_id = " + id;
                PreparedStatement statement = this.connection.prepareStatement(query);;
                ResultSet resultSet = statement.executeQuery();
                if (resultSet.next()) {
                    // Fills in project's attributes
                    foundProject = getBasicProjectFromResultSet(resultSet);
                }

                // Finds project managers
                query = "SELECT project_id, project_manager.user_id, name, email, phonenumber " +
                        "FROM project_manager, fp_user " +
                        "WHERE project_id=" + id + " " +
                        "AND project_manager.user_id = fp_user.user_id";
                statement = this.connection.prepareStatement(query);
                resultSet = statement.executeQuery();
                while (resultSet.next()) {
                    Long userId = resultSet.getLong("user_id");
                    String name = resultSet.getString("name");
                    String email = resultSet.getString("email");
                    String phone = resultSet.getString("phonenumber");
                    foundProject.addManager(new User(userId, name, email, phone));
                }

                // TODO find shoots by project id (ShootDAO)

                // TODO find paperworks by project id (PaperWorkDAO)

                // TODO find client by id (ClientDAO)

                resultSet.close();
                statement.close();

            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
        return foundProject;
    }

    // TODO add method PostgreProjectDAO#findManagersByProjectId(Long id)

    /**
     * Gets all Projects of a manager (a User instance).
     *
     * @param manager the manager we want the project of
     * @return an array of Projects containing the manager's projects
     */
    @Override
    public Project[] findManyByManager(User manager) {
        try {
            List<Project> projects = new ArrayList<>();
            String query = "SELECT * FROM project_manager, project " +
                    "WHERE project_manager.project_id=project.project_id " +
                    "AND user_id=" + manager.getId();
            PreparedStatement statement = this.connection.prepareStatement(query);
            ResultSet resultSet = statement.executeQuery();

            while (resultSet.next()) {
                projects.add(getBasicProjectFromResultSet(resultSet));
            }

            // TODO find by id en fait

            resultSet.close();
            statement.close();
            return projects.toArray(new Project[0]);
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return null;
    }

    // TODO add method PostgreProjectDAO#addManagerToProject(Long id)

    /**
     * Gets all Projects from the database.
     *
     * @return an array containing all Projects present in the database
     */
    @Override
    public Project[] findAll() {
        try {
            List<Project> projects = new ArrayList<>(); // ArrayList is faster for storing and accessing data
            String query = "SELECT project_id FROM project";
            PreparedStatement statement = this.connection.prepareStatement(query);
            ResultSet resultSet = statement.executeQuery();
            while (resultSet.next()) {
                projects.add(this.findById(resultSet.getLong("project_id")));
                // TODO faire pareil pour getManyByManager
            }
            resultSet.close();
            statement.close();
            return projects.toArray(new Project[0]);
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return null;
    }

    /**
     * Deletes a project from the database given its id.
     *
     * @param id the id of the Project to delete
     */
    @Override
    public void deleteById(Long id) {
        if (id != null) {
            try {

                /*
                TODO: find shoots by project id (ShootDAO)
                for each shoot
                    if shoot.date > currentDate
                        ERROR: cannot delete this project
                 */

                this.deleteManagers(id);

                // TODO delete paperwork by project id (PaperWorkDAO)

                // TODO remove client from project (ClientDAO)

                // Deletes Project from project table
                String query = "DELETE FROM project WHERE project_id=" + id;
                PreparedStatement statement = this.connection.prepareStatement(query);
                statement.executeUpdate();

                statement.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }

    /**
     * Updates a project in the database given a Project instance.
     * If the id is null or doesn't exist in the database this method does nothing.
     *
     * @param project the Project instance which will be used to update the project corresponding to the given id
     */
    @Override
    public void updateById(Long id, Project project) {
        if (id != null) {
            try {
                String query = "UPDATE project SET name='" + project.getName() + "', " +
                        "description='" + project.getDescription() + "' " +
                        "WHERE project_id=" + id;
                PreparedStatement statement = this.connection.prepareStatement(query);
                statement.executeUpdate();

                this.deleteManagers(id);
                this.addManagers(id, project.getManagers());

                // TODO update shoots (ShootDAO)

                // TODO update paperworks (PaperworkDAO)

                // TODO update clientId (Project DAO)

                statement.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }


    /*
    Private methods
     */

    /**
     * Deletes the manager's of a project inside the database
     *
     * @param id the id of the project the managers will be deleted from
     * @throws SQLException if the execution of the statement throws a SQLException
     */
    private void deleteManagers(Long id) throws SQLException {
        String query = "DELETE FROM project_manager WHERE project_id=" + id;
        PreparedStatement statement = this.connection.prepareStatement(query);
        statement.executeUpdate();
    }

    /**
     * Adds managers to a given project in the database.
     *
     * @param id the id of the project the managers will be added to
     * @param managers a set of User containing the managers that will be added
     * @throws SQLException if the execution of the statement throws a SQLException
     */
    private void addManagers(Long id, List<User> managers) throws SQLException {
        for (User manager : managers) {
            String query = "INSERT INTO project_manager (project_id, user_id) VALUES (?, ?)";
            PreparedStatement statement = this.connection.prepareStatement(query);
            statement.setLong(1, id);
            statement.setLong(2, manager.getId());
            statement.executeUpdate();
        }
    }

    /**
     * Gets a simple Project instance based on a given ResultSet instance.
     * The ResultSet must be from a query which finds a project.
     * This method does not moves the ResultSet's cursor.
     *
     * @param resultSet the ResultSet from which the project will be instantiated
     * @return a basic Project instance (only id, name and description attributes will be set)
     * @throws SQLException if the ResultSet get methods throws a SQLException
     */
    private Project getBasicProjectFromResultSet(ResultSet resultSet) throws SQLException {
        Long id = resultSet.getLong("project_id");
        String name = resultSet.getString("name");
        String description = resultSet.getString("description");
        return new Project(id, name, description);
    }


    public static void main(String[] args) {
        AbstractDAOFactory factory = PostgreDAOFactory.getInstance();
        ProjectDAO projectDAO = factory.getProjectDAO();
        UserDAO userDAO = factory.getUserDAO();

        User nathan = userDAO.findByEmail("nathan@ndmvisuals.com");
        User merouan = userDAO.findByEmail("merouan@awi.awi");

        Project emotion = projectDAO.findById(16L);
        System.out.println(emotion);
        System.out.println("===================");
        //emotion.addManager(nathan);
        emotion.removeManager(merouan);
        projectDAO.updateById(emotion.getId(), emotion);
        //emotion = projectDAO.findById(16L);
        System.out.println("====================");
        System.out.println(emotion);
    }
}
