package com.filmplanner.dao.postgre;

import com.filmplanner.dao.AbstractDAOFactory;
import com.filmplanner.dao.ProjectDAO;
import com.filmplanner.models.Project;
import com.filmplanner.models.User;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

public class PostgreProjectDAO implements ProjectDAO {

    private Connection connection;

    public PostgreProjectDAO(Connection connection) {
        this.connection = connection;
    }


    /*
    Methods
     */

    /**
     * Creates a new Project in the database given an instance of a Project.
     *
     * @param project the Project which will be inserted inside the database
     * @return an instance of the created project with the id generated by the database; null if there was an SQLException
     */
    @Override
    public Project create(Project project) {
        try {
            String query = "INSERT INTO project (name, description, client_id) VALUES (?, ?, ?)";

            PreparedStatement statement = this.connection.prepareStatement(query, Statement.RETURN_GENERATED_KEYS);
            statement.setString(1, project.getName());
            statement.setString(2, project.getDescription());
            statement.setInt(3, 1);
            // statement.setString(3, client.getId());
            statement.executeUpdate(); // TODO check altered rows number

            ResultSet resultSet = statement.getGeneratedKeys();
            resultSet.next();
            Project createdProject = new Project(resultSet.getInt("id"), resultSet.getString("name"), resultSet.getString("description"));
            statement.close();
            return createdProject;
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return null;
    }

    /**
     * Gets a Project by its id.
     *
     * @param id the Project's id
     * @return the Project corresponding to the given id or null if the id doesn't correspond to any Project.
     */
    @Override
    public Project findById(int id) {
        try {
            String query = "SELECT * FROM project WHERE id=" + id;
            PreparedStatement statement = this.connection.prepareStatement(query);
            ResultSet resultSet = statement.executeQuery();
            resultSet.next();
            Project project = new Project(resultSet.getInt("id"), resultSet.getString("name"), resultSet.getString("description"));
            resultSet.close();
            statement.close();
            return project;
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return null;
    }

    /**
     * Gets all Projects of a manager (a User instance).
     *
     * @param manager the manager we want the project of
     * @return an array of Projects containing the manager's projects
     */
    @Override
    // TODO test method
    public Project[] findManyByManager(User manager) {
        try {
            List<Project> projects = new ArrayList<>();
            String query = "SELECT * FROM project_manager, project WHERE project_id=id AND user_email=" + manager.getEmail();
            PreparedStatement statement = this.connection.prepareStatement(query);
            ResultSet resultSet = statement.executeQuery();
            while (resultSet.next()) {
                projects.add(new Project(resultSet.getString("name"), resultSet.getString("description")));
            }
            resultSet.close();
            statement.close();
            return projects.toArray(new Project[0]);
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return null;
    }

    /**
     * Gets all Projects from the database.
     *
     * @return an array containing all Projects present in the database
     */
    @Override
    public Project[] findAll() {
        try {
            List<Project> projects = new ArrayList<>(); // ArrayList is faster for storing and accessing data
            String query = "SELECT * FROM project";
            PreparedStatement statement = this.connection.prepareStatement(query);
            ResultSet resultSet = statement.executeQuery();
            while (resultSet.next()) {
                projects.add(new Project(resultSet.getInt("id"), resultSet.getString("name"), resultSet.getString("description")));
            }
            resultSet.close();
            statement.close();
            return projects.toArray(new Project[0]);
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return null;
    }

    /**
     * Deletes a project from the database given its id.
     *
     * @param id the id of the Project to delete
     */
    @Override
    public void deleteById(int id) {
        try {
            String query = "DELETE FROM project WHERE id=" + id;
            PreparedStatement statement = this.connection.prepareStatement(query);
            statement.executeUpdate();
            statement.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * Updates a project in the database given a Project instance.
     *
     * @param project the Project instance which will be updated
     */
    @Override
    public void updateById(int id, Project project) {
        try {
            String query = "UPDATE project SET name='" + project.getName() + "', " +
                    "description='" + project.getDescription() + "' " +
                    //" client_id=" + project.getClient().getId()
                    "WHERE id=" + id;
            PreparedStatement statement = this.connection.prepareStatement(query);
            statement.executeUpdate();
            statement.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public static void main(String[] args) {
        AbstractDAOFactory factory = PostgreDAOFactory.getInstance();
        ProjectDAO projectDAO = factory.getProjectDAO();
        Project moanaProject = new Project("Teeeest", "OKKKKK");
        projectDAO.updateById(14, moanaProject);
        for (Project project : projectDAO.findAll()) {
            System.out.println(project);
        }

    }
}
